In [2]:
pip install numpy

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))) - skipping



NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# what is an ARRAY?
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type


# step1 : install the package in the cell or cmd through a command
command = pip install numpy
# step2: import the package 
 import numpy as np
 


# how to create an array?
step1:create a list 

step2:use numpy to change the list into array [np.array]

In [10]:
my_list =  [2,3,4,5,6]

arr = np.array(my_list)

In [14]:
print(arr)

[2 3 4 5 6]


In [21]:
type(arr)

numpy.ndarray

# how to create a multi dimentional array?

In [33]:
#Two dimensional array
my_list1=[2,3,4,5,6]
my_list2=[9,8,7,6,5]
my_list3=[1,2,4,5,3]

In [37]:
newarr=np.array([my_list1,my_list2,my_list3])
print(newarr)

[[2 3 4 5 6]
 [9 8 7 6 5]
 [1 2 4 5 3]]


# how to shape the array?

In [44]:
newarr.shape

(3, 5)

In [46]:
arr.shape

(5,)

# indexing 

In [53]:
arr

array([2, 3, 4, 5, 6])

In [57]:
arr[4]

6

In [59]:
newarr

array([[2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5],
       [1, 2, 4, 5, 3]])

In [61]:
newarr[2:,2:]

array([[4, 5, 3]])

In [63]:
newarr[1:4,:4]

array([[9, 8, 7, 6],
       [1, 2, 4, 5]])

In [65]:
arr

array([2, 3, 4, 5, 6])

# how to add values in the array?
use add()


In [74]:
arr1 = [28,200,200,300,100]
np.array(arr1)

array([ 28, 200, 200, 300, 100])

In [76]:
extended_arr = np.add(arr,arr1)

In [78]:
extended_arr

array([ 30, 203, 204, 305, 106])

# how to change value in the index ?


In [98]:
extended_arr[3:]=100

In [100]:
extended_arr

array([ 30, 203, 204, 100, 100])

In [ ]:
# how to create values ith small commands 

In [116]:
## Create arrays and reshape

arr2=np.arange(0,20).reshape(10,2)

In [118]:
arr2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [120]:
arr3=np.arange(0,30).reshape(3,10)

In [122]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# random distri bution in arrat

In [130]:
arr4=  np.random.rand(3,3)

In [132]:
arr4

array([[0.12074986, 0.4808227 , 0.13008364],
       [0.73353423, 0.69720608, 0.28180549],
       [0.36814109, 0.0766783 , 0.0814452 ]])

In [134]:
#for exponential

arr_ex=np.random.randn(4,4)
arr_ex

array([[-1.01157867, -0.19408009, -0.33215921,  0.16230493],
       [ 0.03384471,  0.46207997,  0.34053057, -2.20475354],
       [ 0.43710448,  0.8600603 , -0.03887923, -0.31299922],
       [ 0.37404782, -1.3962848 , -1.38974997,  0.27625921]])

# how to concate values ?
"Concatenate" means to link or combine two or more things together in a series or sequence. In computing and programming, it often refers to joining strings of text end-to-end to form a single string. For example, if you concatenate "Hello" and "World," you get "HelloWorld."

In [91]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [93]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])